#include "ppc_recomp_shared.h"
#include <cstdio>
#include <cstdlib>
extern void BurnoutReportPpcState();
PPC_FUNC(__imp__HalReturnToFirmware) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__HalReturnToFirmware\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__KeAcquireSpinLockAtRaisedIrql) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__KeAcquireSpinLockAtRaisedIrql\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__KeRaiseIrqlToDpcLevel) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__KeRaiseIrqlToDpcLevel\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__KeReleaseSpinLockFromRaisedIrql) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__KeReleaseSpinLockFromRaisedIrql\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__KeTryToAcquireSpinLockAtRaisedIrql) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__KeTryToAcquireSpinLockAtRaisedIrql\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__KfLowerIrql) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__KfLowerIrql\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__MmQueryAddressProtect) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__MmQueryAddressProtect\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NetDll_XNetXnAddrToInAddr) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NetDll_XNetXnAddrToInAddr\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NetDll_bind) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NetDll_bind\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NetDll_listen) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NetDll_listen\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NtCancelTimer) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NtCancelTimer\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NtOpenFile) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NtOpenFile\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NtQueryDirectoryFile) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NtQueryDirectoryFile\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NtReadFile) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NtReadFile\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__NtSuspendThread) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__NtSuspendThread\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlCaptureContext) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlCaptureContext\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlFreeAnsiString) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlFreeAnsiString\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlInitUnicodeString) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlInitUnicodeString\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlMultiByteToUnicodeN) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlMultiByteToUnicodeN\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlTryEnterCriticalSection) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlTryEnterCriticalSection\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlUnicodeStringToAnsiString) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlUnicodeStringToAnsiString\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__RtlUnwind) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__RtlUnwind\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XAudioGetSpeakerConfig) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XAudioGetSpeakerConfig\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XGetGameRegion) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XGetGameRegion\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XGetLanguage) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XGetLanguage\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XMsgCancelIORequest) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XMsgCancelIORequest\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XMsgStartIORequestEx) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XMsgStartIORequestEx\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XMsgSystemProcessCall) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XMsgSystemProcessCall\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentClose) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentClose\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentCreate) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentCreate\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentCreateEnumerator) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentCreateEnumerator\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentDelete) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentDelete\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentGetCreator) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentGetCreator\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentGetDeviceData) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentGetDeviceData\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentGetDeviceName) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentGetDeviceName\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentGetDeviceState) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentGetDeviceState\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamContentSetThumbnail) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamContentSetThumbnail\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamEnumerate) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamEnumerate\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamGetExecutionId) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamGetExecutionId\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamGetSystemVersion) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamGetSystemVersion\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamInputGetState) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamInputGetState\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamInputSetState) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamInputSetState\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamLoaderGetLaunchData) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamLoaderGetLaunchData\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamLoaderLaunchTitle) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamLoaderLaunchTitle\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamLoaderSetLaunchData) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamLoaderSetLaunchData\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamLoaderTerminateTitle) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamLoaderTerminateTitle\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamParseGamerTileKey) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamParseGamerTileKey\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamReadTileToTexture) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamReadTileToTexture\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowDeviceSelectorUI) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowDeviceSelectorUI\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowDirtyDiscErrorUI) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowDirtyDiscErrorUI\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowGamerCardUIForXUID) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowGamerCardUIForXUID\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowKeyboardUI) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowKeyboardUI\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowMessageBoxUIEx) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowMessageBoxUIEx\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamShowSigninUI) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamShowSigninUI\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamUserAreUsersFriends) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamUserAreUsersFriends\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamUserCheckPrivilege) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamUserCheckPrivilege\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamUserCreateAchievementEnumerator) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamUserCreateAchievementEnumerator\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamUserReadProfileSettings) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamUserReadProfileSettings\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamVoiceClose) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamVoiceClose\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamVoiceCreate) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamVoiceCreate\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamVoiceHeadsetPresent) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamVoiceHeadsetPresent\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__XamVoiceSubmitPacket) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__XamVoiceSubmitPacket\n"); BurnoutReportPpcState(); std::exit(6); }
PPC_FUNC(__imp__vswprintf) { std::fprintf(stdout,"[BOOT IMPORT STOP] __imp__vswprintf\n"); BurnoutReportPpcState(); std::exit(6); }
